### ISSUE TITLE
the installation instruction miss few things

### ISSUE THREAD

**Issue by PiotrCzapla** [wildfish/wildfish-django-starter#2]
Hi,

I tried to follow your installation instructions and it seems that `python manage.py migrate` crash on loading configuration module.

$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from configurations.management import execute_from_command_line
ImportError: No module named 'configurations'

If you intend this skeleton to be used by more ppl you might want to address the installation steps so this error does not appear. 

I will look up how the configurations module works for django and post steps I had to do in order to get your project template to a working state. It might be useful for some other ppl that tries to use your template for the first time.

**Comment by PiotrCzapla** [comment]
It seems that I didn't run `pip install -r requirements.txt`, this solved the issue with configurations module missing :).

Moreover it seems that your template is working only with python 2.x, I had to comment out this two modules to have it start on python3:

django-model-utils
psycopg2

**Comment by rolo** [comment]
Hi Piotr.

That shouldn't be the case - infact, it's now only now tested against Python 3 these days.

If you have a prob with the Python 3 install, please paste the error in here and I'll see if I can spot what the issue might be.

Cheers.

**Comment by jonashagstedt** [comment]
I used this template only yesterday with Python 3 without any issues.
If you run into issues with and error about the `auth_user` migrations run `./manage.py migrate auth` before you run `./manage.py migrate` (this can be an issue if you use Django 1.8.3)

**Comment by rolo** [comment]
Hi Piotr. I'll close this for now - but feel free to post a trace of your install errors and maybe I can help you get to the bottom of it.

**Comment by PiotrCzapla** [comment]
Ok, I was a way traveling,  I will have a look at this this weekend.
If it works for you it is mostlikely some is on my mac.

Cheers,
Piotr
