### ISSUE TITLE
Git Pull on Windows, checkout fails to create {{cookiecutter.model_name|lower}}_list.html

### ISSUE THREAD

**Issue by seanroark** [wildfish/wildfish-django-starter#7]
error: unable to create file {{cookiecutter.project_name}}/templates/{{cookiecutter.app_name}}/{{cookiecutter.model_name|lower}}_list.html (Invalid argument)
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Nothing after this: {{cookiecutter.project_name}}/templates/{{cookiecutter.app_name}} gets created. 
Windows does not allow a pipe in a filename |.

 {{cookiecutter.model_name|lower} is a no go in Windows.

**Comment by rolo** [comment]
Hiya.

Thanks for reporting this. I've not tried to use this on Windows. I wonder if we can perhaps try generating another variable before filename creation?

Leave it with me and I'll try and get access to a machine to try this.

Thanks.

**Comment by rolo** [comment]
@seanroark I believe we've fixed this now. Please test and let us know if any probs.
